apiVersion: v1
kind: Secret
metadata:
  name: fineract-db-secret
type: Opaque
data:
  password: cGFzc3dvcmQ=   # base64('password') à adapter
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fineract-db-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fineract-db-mysql
  template:
    metadata:
      labels:
        app: fineract-db-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: "fineract"
        - name: MYSQL_USER
          value: "fineract"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fineract-db-secret
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fineract-db-secret
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: fineract-db-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: fineract-db-mysql